# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.SmallIntegerField(choices=[(0, '\u6fc0\u6d3b'), (1, '\u91cd\u7f6e\u5bc6\u7801')], verbose_name='\u90ae\u4ef6\u7c7b\u578b')),
                ('code', models.CharField(max_length=40, verbose_name='\u9a8c\u8bc1\u7801')),
                ('create_email', models.DateTimeField(auto_now=True, verbose_name='\u53d1\u9001\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u90ae\u7bb1\u8bb0\u5f55',
                'verbose_name_plural': '\u90ae\u7bb1\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='emailrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
