# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-29 18:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20180426_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivername', models.CharField(max_length=50, verbose_name='\u6536\u8d27\u4eba')),
                ('receivercity', models.CharField(max_length=30, verbose_name='\u57ce\u5e02')),
                ('receivertelephone', models.CharField(max_length=11, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('receiveradress', models.CharField(max_length=300, verbose_name='\u6536\u8d27\u5730\u5740')),
                ('receiveruser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '\u6536\u8d27\u4fe1\u606f',
                'verbose_name_plural': '\u6536\u8d27\u4fe1\u606f',
            },
        ),
    ]
