# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-29 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_receiveruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='receiver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myshop.ReceiverUser'),
        ),
    ]
